# Generated by Django 6.0 on 2026-01-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmtpconfig',
            name='disabled_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usersmtpconfig',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail')], default='gmail', max_length=20),
        ),
    ]
