# Generated by Django 6.0 on 2026-01-03 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersmtpconfig_disabled_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmtpconfig',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='usersmtpconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usersmtpconfig',
            unique_together={('user', 'smtp_email')},
        ),
    ]
