# Generated by Django 5.1.3 on 2026-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactgroup_contactgroupcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmtpconfig',
            name='auth_type',
            field=models.CharField(choices=[('app_password', 'App Password'), ('oauth_refresh_token', 'OAuth Refresh Token')], default='app_password', max_length=30),
        ),
        migrations.AddField(
            model_name='usersmtpconfig',
            name='encrypted_refresh_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersmtpconfig',
            name='encrypted_app_password',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
