# Generated by Django 5.1.3 on 2026-02-11 00:16

from django.db import migrations


def delete_legacy_app_password_configs(apps, schema_editor):
    UserSMTPConfig = apps.get_model('api', 'UserSMTPConfig')
    UserSMTPConfig.objects.filter(auth_type='app_password').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usersmtpconfig_auth_type_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_legacy_app_password_configs, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='usersmtpconfig',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='usersmtpconfig',
            name='encrypted_app_password',
        ),
    ]
