# Generated by Django 5.1.3 on 2026-02-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_usersmtpconfig_auth_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=4, unique=True)),
                ("text", models.TextField(blank=True)),
                ("file_data", models.BinaryField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_content_type", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
