# Generated by Django 5.1.15 on 2026-04-27 10:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_toolreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsubscription',
            name='paypal_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='chatbotsubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='customchatbot',
            name='public_id',
            field=models.CharField(default=api.models._generate_public_id, help_text='Random URL-safe token used in public share links.', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='savedcsv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
