# Generated by Django 5.1.15 on 2026-04-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_paypal_subscription_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotsubscription',
            name='razorpay_customer_id',
        ),
        migrations.RemoveField(
            model_name='chatbotsubscription',
            name='razorpay_status',
        ),
        migrations.RemoveField(
            model_name='chatbotsubscription',
            name='razorpay_subscription_id',
        ),
        migrations.RemoveField(
            model_name='chatbotsubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='chatbotsubscription',
            name='stripe_status',
        ),
        migrations.RemoveField(
            model_name='chatbotsubscription',
            name='stripe_subscription_id',
        ),
    ]
